config/routes.rb
Rails.application.routes.draw do
  root to: 'home#index'

  resources :orders
  resources :products
  resources :customers
  resources :tables
  resources :waiters
  resources :stores
  resources :categories
  devise_for :users
  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/store.rb
class Store < ApplicationRecord
  include RailsAdminCharts
  validates_presence_of :name, :phone, :tax_rate
  validates_uniqueness_of :name, :phone, :website
end

app/controllers/stores_controller.rb
class StoresController < ApplicationController
  before_action :set_store, only: [:show, :edit, :update, :destroy]
  before_action :authenticate_user!
  before_action :set_authorize, only: [:index, :destroy]
  after_action :verify_authorized, only: [:index, :destroy]

  # GET /stores
  def index
    @stores = Store.all
    respond_to do |format|
      format.html { render :index }
      format.pdf do
        pdf = StoresPdf.new(@stores)
        send_data pdf.render, filename: 'stores.pdf', type: 'application/pdf', disposition: 'inline'
      end
    end
  end

  # GET /stores/1
  def show
  end

  # GET /stores/new
  def new
    @store = Store.new
  end

  # GET /stores/1/edit
  def edit
  end

  # POST /stores
  def create
    @store = Store.new(store_params)

    if @store.save
      redirect_to @store, notice: 'Store was successfully created.'
    else
      render :new
    end
  end

  # PATCH/PUT /stores/1
  def update
    if @store.update(store_params)
      redirect_to @store, notice: 'Store was successfully updated.'
    else
      render :edit
    end
  end

  # DELETE /stores/1
  def destroy
    @store.destroy if @store.present?
    redirect_to stores_url, notice: 'Store was successfully destroyed.'
  end

  private
  # Use callbacks to share common setup or constraints between actions.
  def set_store
    @store = Store.find(params[:id])
  rescue ActiveRecord::RecordNotFound
    Rails.logger.error{ 'Store record is not found' }
    redirect_to root_url, notice: 'Data is not found !'
  end

  # Only allow a trusted parameter "white list" through.
  def store_params
    params.require(:store).permit(:name, :description, :phone, :address, :tax_rate, :website)
  end

  # set authorizarion in model
  def set_authorize
    authorize Store
  end

end

app/helpers/stores_helper.rb
module StoresHelper
end

app/views/stores/_form.html.erb
<%= form_with(model: store, local: true) do |form| %>
  <% if store.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(store.errors.count, "error") %> prohibited this store from being saved:</h2>

      <ul>
      <% store.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :name %>
    <%= form.text_field :name, id: :store_name %>
  </div>

  <div class="field">
    <%= form.label :description %>
    <%= form.text_area :description, id: :store_description %>
  </div>

  <div class="field">
    <%= form.label :phone %>
    <%= form.text_field :phone, id: :store_phone %>
  </div>

  <div class="field">
    <%= form.label :address %>
    <%= form.text_field :address, id: :store_address %>
  </div>

  <div class="field">
    <%= form.label :tax_rate %>
    <%= form.text_field :tax_rate, id: :store_tax_rate %>
  </div>

  <div class="field">
    <%= form.label :website %>
    <%= form.text_field :website, id: :store_website %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/stores/edit.html.erb
<h1>Editing Store</h1>

<%= render 'form', store: @store %>

<%= link_to 'Show', @store %> |
<%= link_to 'Back', stores_path %>

app/views/stores/index.html.erb
<div class="row">
  <div class="col-xs-12 col-md-12">
    <div class="box">
      <div class="box-header">
        <div class=" col-md-6 col-xs-6">
          <h3 class="box-title">Stores Report
            <%= link_to 'Download PDF', stores_path(format: :pdf), class: 'btn btn-sm btn-success', target: :blank %>
            <%= link_to 'Download others', rails_admin.export_path('store'), class: 'btn btn-sm btn-info', target: :blank %>
            <%= link_to 'See charts', rails_admin.charts_path('store'), class: 'btn btn-sm btn-primary', target: :blank %>
          </h3>
        </div>
      </div>
      <!-- /.box-header -->
      <div class="box-body">
        <table id="example1" class="table table-bordered table-striped">
          <thead>
          <tr>
            <th>No.</th>
            <th>Name</th>
            <th>Description</th>
            <th>Phone</th>
            <th>Address</th>
            <th>Tax rate</th>
            <th>Website</th>
          </tr>
          </thead>
          <tbody>
          <% @stores.each_with_index do |store, index| %>
            <tr>
              <td><%= index+1 %></td>
              <td><%= store.name %></td>
              <td><%= store.description %></td>
              <td><%= store.phone %></td>
              <td><%= store.address %></td>
              <td><%= store.tax_rate %><%= '%' %></td>
              <td><%= store.website %></td>
            </tr>
          <% end %>
          </tbody>
          <tfoot>
          <tr>
            <th>No.</th>
            <th>Name</th>
            <th>Description</th>
            <th>Phone</th>
            <th>Address</th>
            <th>Tax rate</th>
            <th>Website</th>
          </tr>
          </tfoot>
        </table>
      </div>
      <!-- /.box-body -->
    </div>
    <!-- /.box -->
  </div>
  <!-- /.col -->
</div>
<!-- /.row -->

app/views/stores/new.html.erb
<h1>New Store</h1>

<%= render 'form', store: @store %>

<%= link_to 'Back', stores_path %>

app/views/stores/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @store.name %>
</p>

<p>
  <strong>Description:</strong>
  <%= @store.description %>
</p>

<p>
  <strong>Phone:</strong>
  <%= @store.phone %>
</p>

<p>
  <strong>Address:</strong>
  <%= @store.address %>
</p>

<p>
  <strong>Tax rate:</strong>
  <%= @store.tax_rate %>
</p>

<p>
  <strong>Website:</strong>
  <%= @store.website %>
</p>

<%= link_to 'Edit', edit_store_path(@store) %> |
<%= link_to 'Back', stores_path %>