config/routes.rb
Rails.application.routes.draw do
  root to: 'home#index'

  resources :orders
  resources :products
  resources :customers
  resources :tables
  resources :waiters
  resources :stores
  resources :categories
  devise_for :users
  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  before_action :authenticate_user!
  def index
    @open = Order.pending
    @sales = Order.payed

    payed_today = @sales.today
    @day_sales = payed_today.count
    @day_income = sum_income payed_today
    @day_customers = Customer.today.count
  end

  # sums orders income payed today
  def sum_income(payed_today)
    res = 0
    payed_today.each { |order| res += order.net unless order.net.nil? } unless payed_today.nil?
    res
  end
end

app/helpers/home_helper.rb
module HomeHelper
  include OrdersHelper
end

app/views/home/index.html.erb
<% unless notice.nil? %>
  <div class="alert alert-info">
    <p id="notice"><%= notice %></p>
  </div>
<% end %>

<div class="row">

  <div class="col-md-8">

    <div class="panel panel-default">
      <div class="panel-heading">Open Orders</div>

      <table class="table">
        <thead>
        <tr>
          <th>Waiter</th>
          <th>Tables</th>
          <th>Sub Total</th>
          <th>Discount</th>
          <th>Net</th>
          <th>Update At</th>
          <th colspan="3"></th>
        </tr>
        </thead>

        <tbody>
        <% @open.each do |order| %>
          <tr>
            <td><%= order.waiter.name unless order.waiter.nil? %></td>
            <td><%= tables_list order %></td>
            <td><span class="label label-warning">$<%= order.brute %></span></td>
            <td><span class="label label-danger">$<%= order.discount %></span></td>
            <td><span class="label label-primary">$<%= order.net %></span></td>
            <td><%= order.updated_at %></td>
            <td><%= link_to "Checkout", edit_order_path(order), class: 'btn btn-sm btn-info' %></td>
          </tr>
        <% end %>
        </tbody>
      </table>

    </div>

    <div class="panel panel-default">
      <div class="panel-heading">Latest Sales</div>

      <table class="table">
        <thead>
        <tr>
          <th>Waiter</th>
          <th>Tables</th>
          <th>Sub Total</th>
          <th>Discount</th>
          <th>Net</th>
          <th>Payed At</th>
          <th colspan="3"></th>
        </tr>
        </thead>

        <tbody>
        <% @sales.each do |order| %>
          <tr>
            <td><%= order.waiter.name %></td>
            <td><%= tables_list order %></td>
            <td><span class="label label-warning">$<%= order.brute %></span></td>
            <td><span class="label label-danger">$<%= order.discount %></span></td>
            <td><span class="label label-primary">$<%= order.net %></span></td>
            <td><%= order.payed_at %></td>
            <td><%= link_to 'Review', rails_admin.show_path('order', order.id), class: 'btn btn-sm btn-primary' %></td>
            <td><%= link_to 'Invoice', order_path(order, format: :pdf), class: 'btn btn-sm btn-success', target: :blank %></td>
          </tr>
        <% end %>
        </tbody>
      </table>

    </div>
  </div>

  <div class="col-md-4">

    <div class="btn-group spacer-bottom" role="group" aria-label="...">
      <%= link_to "New Order", new_order_url, class: 'btn btn-success' %>

      <button type="button" class="btn btn-default dropdown-toggle" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
        Actions
        <span class="caret"></span>
      </button>
      <ul class="dropdown-menu">
        <li><%= link_to "All Customers", rails_admin.index_path('customer') %></li>
        <li><%= link_to "New Customer", rails_admin.new_path('customer') %></li>
        <li><%= link_to "View Products", rails_admin.index_path('product'), 'data-no-turbolink' => true %></li>
      </ul>
    </div>
    <br/></br>

    <div class="panel panel-default">
      <div class="panel-heading">Today Sales</div>

      <ul class="list-group">
        <li class="list-group-item">
          Orders: <span class="badge badge-info"><%= @day_sales %></span>
        </li>
        <li class="list-group-item">
          Income: <span class="badge badge-info"><%= @day_income %></span>
        </li>
        <li class="list-group-item">
          New Customers: <span class="badge badge-info"><%= @day_customers %></span>
        </li>
      </ul>
    </div>
  </div>
</div>