config/routes.rb
Rails.application.routes.draw do
  root to: 'home#index'

  resources :orders
  resources :products
  resources :customers
  resources :tables
  resources :waiters
  resources :stores
  resources :categories
  devise_for :users
  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/category.rb
class Category < ApplicationRecord
  include RailsAdminCharts
  validates_presence_of :name
  validates_uniqueness_of :name
  has_many :products, dependent: :destroy
end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController
  before_action :set_category, only: [:show, :edit, :update, :destroy]
  before_action :authenticate_user!
  before_action :set_authorize, only: [:index, :destroy]
  after_action :verify_authorized, only: [:index, :destroy]

  # GET /categories
  def index
    @categories = Category.all
    respond_to do |format|
      format.html { render :index }
      format.pdf do
        pdf = CategoriesPdf.new(@categories)
        send_data pdf.render, filename: 'categories.pdf', type: 'application/pdf', disposition: 'inline'
      end
    end
  end

  # GET /categories/1
  def show
  end

  # GET /categories/new
  def new
    @category = Category.new
  end

  # GET /categories/1/edit
  def edit
  end

  # POST /categories
  def create
    @category = Category.new(category_params)

    if @category.save
      redirect_to @category, notice: 'Category was successfully created.'
    else
      render :new
    end
  end

  # PATCH/PUT /categories/1
  def update
    if @category.update(category_params)
      redirect_to @category, notice: 'Category was successfully updated.'
    else
      render :edit
    end
  end

  # DELETE /categories/1
  def destroy
    @category.destroy if @category.present?
    redirect_to categories_url, notice: 'Category was successfully destroyed.'
  end

  private
  # Use callbacks to share common setup or constraints between actions.
  def set_category
    @category = Category.find(params[:id])
  rescue ActiveRecord::RecordNotFound
    Rails.logger.error{ 'Category record is not found' }
    redirect_to root_url, notice: 'Data is not found !'
  end

  # Only allow a trusted parameter "white list" through.
  def category_params
    params.require(:category).permit(:name, :description)
  end

  # set authorizarion in model
  def set_authorize
    authorize Category
  end
end

app/helpers/categories_helper.rb
module CategoriesHelper
end

app/views/categories/_form.html.erb
<%= form_with(model: category, local: true) do |form| %>
  <% if category.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(category.errors.count, "error") %> prohibited this category from being saved:</h2>

      <ul>
      <% category.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :name %>
    <%= form.text_field :name, id: :category_name, required: 'required' %>
  </div>

  <div class="field">
    <%= form.label :description %>
    <%= form.text_area :description, id: :category_description %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/categories/edit.html.erb
<h1>Editing Category</h1>

<%= render 'form', category: @category %>

<%= link_to 'Show', @category %> |
<%= link_to 'Back', categories_path %>

app/views/categories/index.html.erb
<div class="row">
  <div class="col-xs-12 col-md-12">
    <div class="box">
      <div class="box-header">
        <div class=" col-md-6 col-xs-6">
          <h3 class="box-title">Categories Report
            <%= link_to 'Download PDF', categories_path(format: :pdf), class: 'btn btn-sm btn-success', target: :blank %>
            <%= link_to 'Download others', rails_admin.export_path('category'), class: 'btn btn-sm btn-info', target: :blank %>
            <%= link_to 'See charts', rails_admin.charts_path('category'), class: 'btn btn-sm btn-primary', target: :blank %>
          </h3>
        </div>
      </div>
      <!-- /.box-header -->
      <div class="box-body">
        <table id="example1" class="table table-bordered table-striped">
          <thead>
          <tr>
            <th>No.</th>
            <th>Name</th>
            <th>Description</th>
          </tr>
          </thead>
          <tbody>
          <% @categories.each_with_index do |category, index| %>
            <tr>
              <td><%= index+1 %></td>
              <td><%= category.name %></td>
              <td><%= category.description %></td>
            </tr>
          <% end %>
          </tbody>
          <tfoot>
          <tr>
            <th>No.</th>
            <th>Name</th>
            <th>Description</th>
          </tr>
          </tfoot>
        </table>
      </div>
      <!-- /.box-body -->
    </div>
    <!-- /.box -->
  </div>
  <!-- /.col -->
</div>
<!-- /.row -->

app/views/categories/new.html.erb
<h1>New Category</h1>

<%= render 'form', category: @category %>

<%= link_to 'Back', categories_path %>

app/views/categories/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @category.name %>
</p>

<p>
  <strong>Description:</strong>
  <%= @category.description %>
</p>

<%= link_to 'Edit', edit_category_path(@category) %> |
<%= link_to 'Back', categories_path %>