config/routes.rb
Rails.application.routes.draw do
  root to: 'home#index'

  resources :orders
  resources :products
  resources :customers
  resources :tables
  resources :waiters
  resources :stores
  resources :categories
  devise_for :users
  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/category.rb
class Category < ApplicationRecord
  include RailsAdminCharts
  validates_presence_of :name
  validates_uniqueness_of :name
  has_many :products, dependent: :destroy
end

app/models/customer.rb
class Customer < ApplicationRecord
  include SharedScopes
  include RailsAdminCharts
  validates_presence_of :name, :address
  validates_uniqueness_of :email, :phone
  has_many :orders, dependent: :destroy
end

app/models/order.rb
class Order < ApplicationRecord
  include RailsAdminCharts
  include OrdersHelper
  include SharedScopes

  belongs_to :customer
  belongs_to :waiter
  validates_presence_of :brute, :net
  has_and_belongs_to_many :products, dependent: :destroy
  has_and_belongs_to_many :tables, dependent: :destroy
  scope :pending, -> { where(payed: false) }
  scope :payed, -> { where(payed: true).order(payed_at: 'desc') }
end

app/models/product.rb
class Product < ApplicationRecord
  include RailsAdminCharts
  belongs_to :category
  validates_presence_of :name, :price
  validates_uniqueness_of :name

  def name_with_price
    "#{self.name} - $#{self.price}"
  end
end

app/models/store.rb
class Store < ApplicationRecord
  include RailsAdminCharts
  validates_presence_of :name, :phone, :tax_rate
  validates_uniqueness_of :name, :phone, :website
end

app/models/table.rb
class Table < ApplicationRecord
  include RailsAdminCharts
  validates_presence_of :name, :capacity
  validates_uniqueness_of :name
end

app/models/user.rb
class User < ApplicationRecord
  include RailsAdminCharts
  enum role: [:staff, :admin]
  after_initialize :set_default_role, if: :new_record?

  def set_default_role
    self.role ||= :staff
  end

  validates_presence_of :name
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/models/waiter.rb
class Waiter < ApplicationRecord
  include RailsAdminCharts
  validates_presence_of :name, :address, :phone
  validates_uniqueness_of :phone
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  before_action :authenticate_user!
  def index
    @open = Order.pending
    @sales = Order.payed

    payed_today = @sales.today
    @day_sales = payed_today.count
    @day_income = sum_income payed_today
    @day_customers = Customer.today.count
  end

  # sums orders income payed today
  def sum_income(payed_today)
    res = 0
    payed_today.each { |order| res += order.net unless order.net.nil? } unless payed_today.nil?
    res
  end
end

app/controllers/orders_controller.rb
class OrdersController < ApplicationController
  before_action :set_order, only: [:show, :edit, :update, :destroy]
  before_action :authenticate_user!
  before_action :set_authorize, only: [:index, :destroy]
  after_action :verify_authorized, only: [:index, :destroy]

  # GET /orders
  def index
    @orders = Order.all
    respond_to do |format|
      format.html { render :index }
      format.pdf do
        pdf = OrdersPdf.new(@orders)
        send_data pdf.render, filename: 'orders.pdf', type: 'application/pdf', disposition: 'inline'
      end
    end
  end

  # GET /orders/1
  def show
    respond_to do |format|
      format.html { render :show }
      format.pdf do
        @store = Store.first
        pdf = InvoicePdf.new(@order, @store)
        send_data pdf.render, filename: "invoice-#{ @order.id }.pdf", type: 'application/pdf', disposition: 'inline'
      end
    end
  end

  # GET /orders/new
  def new
    @order = Order.new
  end

  # GET /orders/1/edit
  def edit
  end

  # POST /orders
  def create
    @order = Order.new(order_params)

    if @order.save
      redirect_to root_path, notice: 'Order was successfully created.'
    else
      render :new
    end
  end

  # PATCH/PUT /orders/1
  def update
    if @order.update(order_params)
      redirect_to root_path, notice: 'Order was successfully updated.'
    else
      render :edit
    end
  end

  # DELETE /orders/1
  def destroy
    @order.destroy if @order.present?
    redirect_to root_path, notice: 'Order was successfully destroyed.'
  end

  private
  # Use callbacks to share common setup or constraints between actions.
  def set_order
    @order = Order.find(params[:id])
  rescue ActiveRecord::RecordNotFound
    Rails.logger.error{ 'Order record is not found' }
    redirect_to root_url, notice: 'Data is not found !'
  end

  # Only allow a trusted parameter "white list" through.
  def order_params
    params.require(:order).permit(:discount, :brute, :net, :payed, :payed_at, :customer_id, :waiter_id, product_ids: [], table_ids: [])
  end

  # set authorizarion in model
  def set_authorize
    authorize Order
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def app_name
    if Store.first.present?
      name = Store.first.name
    else
      name = 'Restaurant POS'
    end
    name
  end

  def bootstrap_class_for(flash_type)
    { alert: 'alert-danger', notice: 'alert-success' }[flash_type.to_sym] || flash_type.to_s
  end

  def bootstrap_icon_for(flash_type)
    { alert: 'warning-sign', notice: 'ok-circle' }[flash_type.to_sym] || 'question-sign'
  end

  def flash_messages
    flash.each do |msg_type, message|
      concat(content_tag(:div, message, class: "alert #{bootstrap_class_for(msg_type)} fade in") do
        concat content_tag(:button, 'x', class: 'close', data: { dismiss: 'alert' })
        concat content_tag(:i, nil, class: "glyphicon glyphicon-#{bootstrap_icon_for(msg_type)}")
        concat '  '
        concat message
      end)
    end
    nil
  end
end

app/helpers/categories_helper.rb
module CategoriesHelper
end

app/helpers/customers_helper.rb
module CustomersHelper
end

app/helpers/home_helper.rb
module HomeHelper
  include OrdersHelper
end

app/helpers/orders_helper.rb
module OrdersHelper
  def tables_list(order=self)
    order = self if order.nil?

    res = ''
    order.tables.each_with_index do |x, i|
      l = order.tables.length
      res += x.name
      res += ', ' unless i+1 == l
    end
    res
  end
end

app/helpers/products_helper.rb
module ProductsHelper
end

app/helpers/stores_helper.rb
module StoresHelper
end

app/helpers/tables_helper.rb
module TablesHelper
end

app/helpers/waiters_helper.rb
module WaitersHelper
end

app/views/layouts/_header.html.erb
<!-- Fixed navbar -->
<nav class="navbar navbar-default navbar-fixed-top">
  <div class="container">
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar" aria-expanded="false" aria-controls="navbar">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <%= link_to app_name, root_url, class: 'navbar-brand' %>
    </div>

    <% if user_signed_in? %>
      <div id="navbar" class="navbar-collapse collapse">
        <ul class="nav navbar-nav">
          <li><%= link_to "Home", root_url %></li>
          <% if current_user.admin? %>
            <li class="dropdown">
              <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">
                Reports <span class="caret"></span>
              </a>
              <ul class="dropdown-menu">
                <li><%= link_to :categories.to_s.titleize, categories_path %></li>
                <li><%= link_to :customers.to_s.titleize, customers_path %></li>
                <li><%= link_to :orders.to_s.titleize, orders_path %></li>
                <li><%= link_to :products.to_s.titleize, products_path %></li>
                <li><%= link_to :stores.to_s.titleize, stores_path %></li>
                <li><%= link_to :tables.to_s.titleize, tables_path %></li>
                <li><%= link_to :waiters.to_s.titleize, waiters_path %></li>
              </ul>
            </li>
          <% end %>
        </ul>


        <ul class="nav navbar-nav navbar-right">
          <li><%= link_to "Admin", rails_admin.dashboard_path, 'data-no-turbolink': true %></li>
          <li class="dropdown">
            <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">
              <%= current_user.name %> <span class="caret"></span>
            </a>
            <ul class="dropdown-menu">
              <li><%= link_to('Logout', destroy_user_session_path, method: :delete) %></li>
            </ul>
          </li>
        </ul>
      </div>
    <% end %>
    <!--/.nav-collapse -->
  </div>
</nav>
<br/><br/><br/><br/>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title><%= app_name %></title>
  <%= csrf_meta_tags %>
  <!--Reset CSS-->
  <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': true %>
</head>
<body>

<%= render "layouts/header" %>
<%= render 'shared/flash_notice'  %>
<div class="container">
    <%= yield %>
</div>

<!-- javascript start -->
<%= javascript_include_tag 'application', 'data-turbolinks-track': true %>
<!-- javascript end -->

</body>
</html>

app/views/shared/_flash_notice.html.erb
<div class="row">
  <div class="col-md-6 col-md-offset-3">
    <%= flash_messages %>
  </div>
</div>